### ISSUE TITLE
mybatis中 mapper文件使用 <collection> 查询会抱空指针异常

### ISSUE THREAD

**Issue by qiaoqiao888** [heykb/mybatis-sqlhelper#3]
![image](https://user-images.githubusercontent.com/18333714/185794075-cb62c6f4-7b7e-4e01-8d26-9e7dd39f7fb7.png)

移除掉mybatis-sqlhelper-spring-boot-starter 可以正常查询 应该是sqlstement 设置有问题 没有细查

**Comment by qiaoqiao888** [comment]
![image](https://user-images.githubusercontent.com/18333714/185794211-c3c47046-db29-4f60-901f-23a654c9c4e2.png)

**Comment by heykb** [comment]
> ![image](https://user-images.githubusercontent.com/18333714/185794211-c3c47046-db29-4f60-901f-23a654c9c4e2.png)
哪个版本

**Comment by heykb** [comment]
> ![image](https://user-images.githubusercontent.com/18333714/185794075-cb62c6f4-7b7e-4e01-8d26-9e7dd39f7fb7.png)
> 
> 移除掉mybatis-sqlhelper-spring-boot-starter 可以正常查询 应该是sqlstement 设置有问题 没有细查
使用版本  3.0.0.SR1

**Comment by heykb** [comment]
@qiaoqiao888 使用版本 3.0.0.SR1

**Comment by qiaoqiao888** [comment]
这个版本可以。

**Comment by qiaoqiao888** [comment]
发个正式版本么 大佬

**Comment by heykb** [comment]
@qiaoqiao888  发了
