### ISSUE TITLE
集成插件后,第一次新增能成功,后面再新增就报错

### ISSUE THREAD

**Issue by tuboshuya** [heykb/mybatis-sqlhelper#6]
大佬,我在使用注入租户id和创建人功能的时候,新增数据的时候第一次正常,后面再新增数据的时候就会异常java.sql.SQLException: No value specified for parameter,注入之后少了parameter,请问是什么原因?
使用的依赖版本如下:
![image](https://github.com/heykb/mybatis-sqlhelper/assets/54307581/42d0fd21-3081-499a-b717-9604210e00b0)
mybatis-config.xml配置如下:
![image](https://github.com/heykb/mybatis-sqlhelper/assets/54307581/8257fb97-a9c0-47e2-a5ff-49e59f77aebd)
拦截器配置如下:
![image](https://github.com/heykb/mybatis-sqlhelper/assets/54307581/71b51011-60bc-41a1-b351-4935f322e6d0)
两次新增操作的日志如下:
成功的新增:
![image](https://github.com/heykb/mybatis-sqlhelper/assets/54307581/824094b5-b7b0-47c2-babe-963c7efdc27b)
失败的新增:
![image](https://github.com/heykb/mybatis-sqlhelper/assets/54307581/3b22fac5-c0a1-437f-9f53-41e8bbf05eb8)

**Comment by heykb** [comment]
@tuboshuya 你好啊。首先多个handle配置，value逗号分割多个handler，不用配置多个一样的plugin。

**Comment by tuboshuya** [comment]
@heykb 你好,我把插件的配置改到MabtisCongfig中了,改动如下
![image](https://github.com/heykb/mybatis-sqlhelper/assets/54307581/fd24b7f6-bf97-4d73-9898-87b558088458)
但还是一样的问题,当我用mabtis的insert方法新增时,第一次可以成功,但是后面的都因为缺了param报错,将新增方法改成insertSelective就没这个问题了,请问插件是只支持insertSelective这个方法吗?还是我insert用的有问题?

**Comment by heykb** [comment]
@tuboshuya 你好。我不是很明白你图中改动的意思。我的意思是配置多个handler用逗号分割，不要配置多个plugin
```xml
<plugin interceptor="io.github.heykb.sqlhelper.interceptor.SqlHelperPlugin">
       <property name="InjectColumnInfoHandler'
value="com.dataplatform.framework.interceptor.mybatis.SimpleTenantInfoHandler,com.dataplatform.framework.interceptor.mybatis.CreateByInjectColumnHandler"/>
</plugin>
```

其次insertSelective是什么方法，你使用了什么其他辅助框架吗，mybatis-plus or tk-mybaits?

**Comment by tuboshuya** [comment]
@heykb 你好,第一次贴的图我有改动,handler改成了@Component方式注入,mabatis-config删除plugin了配置(这里不是重点,无论是component注入方式还是plugin配置方式,在用mapper的insert方法新增时,第二次均会报错)
![image](https://github.com/heykb/mybatis-sqlhelper/assets/54307581/1407f8b6-5e8b-48c8-8d84-4b45f70ee395)
mybatis生成的Mapper文件里面,有两个新增方法,分别为insert和insertSelective,如下图:
![image](https://github.com/heykb/mybatis-sqlhelper/assets/54307581/046b1e71-9ad9-4c65-bdea-9e8f700f65b2)
![image](https://github.com/heykb/mybatis-sqlhelper/assets/54307581/9bd1f16b-ad41-4a5b-b1b8-70e353a42a72)
使用逆向工程生成mapper自带的insert方法新增时,第一次可以新增成功,第二次就会报错,使用mapper自带的insertSelective方法新增时就没有问题,请问大佬这是什么原因呢?
